name: Publish package to registry

on:
  release:
    types:
      - released

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1
          registry-url: https://registry.npmjs.org/

      - name: Setup package manager
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure git user email
        run: git config --global user.email "${{ github.event.release.author.email }}"

      - name: Configure git user name
        run: git config --global user.name "${{ github.event.release.author.login }}"

      - name: Change package version
        run: pnpm version ${{ github.event.release.tag_name }}

      - name: Install @nestjs/cli globally
        run: npm i -g @nestjs/cli

      - name: Build package and bundle source
        run: pnpm build

      - name: Publish package to registry
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
